name: Build Harbour for DOS in harbour-exercise

on:
  push:
    branches: [main, master]
  pull_request:
  workflow_dispatch:

jobs:
  build-dos:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Harbour repository
        uses: actions/checkout@v4
        with:
          repository: woodhead2019/harbour
          ref: master

      - name: Setup Open Watcom
        uses: open-watcom/setup-watcom@v0
        with:
          version: "2.0"

      - name: Debug Watcom Setup
        run: |
          echo "WATCOM path: $WATCOM"
          ls -la $WATCOM/binl/ || echo "binl directory not found"
          $WATCOM/binl/wcc386 -h || echo "Watcom test failed - check logs"
          echo "INCLUDE path: $INCLUDE"

      - name: Build Host Harbour (Linux)
        run: |
          export PATH=$WATCOM/binl:$PATH
          export INCLUDE=$WATCOM/h  # 强制使用 Watcom 头文件
          make clean
          make -j$(nproc)  # 构建 Linux 版本的 Harbour
          ls -la bin/  # 检查生成的工具

      - name: Build Harbour for DOS
        env:
          WATCOM: ${{ env.WATCOM }}
          HB_PLATFORM: dos
          HB_COMPILER: watcom
          HB_HOST_BIN: /home/runner/work/harbour-exercise/harbour-exercise/bin  # 设置主机工具路径
        run: |
          export PATH=$WATCOM/binl:$PATH
          export INCLUDE=$WATCOM/h  # 再次确保正确头文件路径
          make clean
          make -j$(nproc) HB_BUILD_3RD=no  # 禁用第三方库以避免 PNG 错误

      - name: Package DOS binaries
        run: |
          mkdir -p harbour-dos-bin
          find bin -name "*.exe" -exec cp {} harbour-dos-bin/ \; || echo "No .exe files found"
          if [ -d harbour-dos-bin ] && [ "$(ls -A harbour-dos-bin)" ]; then
            tar -czf harbour-dos.tar.gz -C harbour-dos-bin .
            echo "Packaged $(ls harbour-dos-bin | wc -l) binaries"
          else
            echo "No binaries to package"
            exit 1
          fi
      
      - name: Upload DOS binaries
        uses: actions/upload-artifact@v4
        with:
          name: harbour-dos-binaries
          path: harbour-dos.tar.gz
          if-no-files-found: warn
