name: Test-DOS-Env

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: 安装极简依赖（仅 qemu-utils + unzip）
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y qemu-utils unzip

      - name: 运行 build-dos-env.sh
        run: bash ./build-dos-env.sh

      # 如需真正启动 DOS，再装完整 QEMU
      - name: 可选：安装完整 QEMU 并验证镜像
        run: |
          sudo apt-get install -y qemu-system-x86 dosfstools
          file dos.img
